settings:
  title: 'Status Page'
  url: 'status.naodeng.com.cn' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: naodeng.com.cn # unique identifier
    name: naodeng.com.cn
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://naodeng.com.cn/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: inaodeng.com
    name: inaodeng.com
    description: 'Built for anything connected to the Internet.'
    url: 'https://inaodeng.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: email.naodeng.com.cn
    name: email.naodeng.com.cn
    description: 'Built for anything connected to the Internet.'
    url: 'https://email.naodeng.com.cn'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
